### ISSUE TITLE
Zobrazení použitého kodeku ve streamu

### ISSUE THREAD

**Issue by skvrnda** [ljsydpwym/StremioCinema#14]
Při výběru streamu hraje často roli kodek. Při stejné velkiosti a rozlišení streamu, je např. HEVC výrazně kvalitnější než H264, tudíž pokud mám zařízení, které je schopné přehrát HEVC, dám mu přednost před H264 a naopak, pokud nemám zařízení se schopností dekódovat v reálném čase HEVC, zvolím raději stream s méně efektivním kodekem. Z toho důvodu by bylo vhodné kodek u streamu zobrazit, ideálně ve štítku "Video".

![obrazek](https://github.com/ljsydpwym/StremioCinema/assets/42358093/41bb2d48-804d-4603-b6d1-5fe26abc9196)

**Comment by ljsydpwym** [comment]
Implementovane ako posledna hodnota vramci video fieldu. Priklad: FullHD-HEVC
