### ISSUE TITLE
Novinky > 30 posledních titulů

### ISSUE THREAD

**Issue by skvrnda** [ljsydpwym/StremioCinema#15]
Aktuálně se v sekcích z SCC zobrazuje jen posledních 30 titulů, což zjevně souvisí s optimalizací SCC služby pro stránkování titulů v KODI. Většina addonů ve Stremio umožňuje vylistovat více než 30 titulů. Zde to nejspíš bez limitu nepůjde, ale bylo by fajn mít ten limit vyšší než 30, alespoň 90.
/filter/v2/news bude nejspíš potřeba zavolat opakoveně v cyklu (from=0..2)

**Comment by ljsydpwym** [comment]
Po novom je to konfigurovatelne v nastaveniach addonu pred instalaciou. Vyssie cislo ale sposobi pomalsie nacitanie, obzvlast ak sa skombinuje s povolenym TMDB
