### ISSUE TITLE
LG webOS stream error

### ISSUE THREAD

**Issue by strof1x** [ljsydpwym/StremioCinema#18]
Prečítať prosím najprv image.

![IMG_4293](https://github.com/ljsydpwym/StremioCinema/assets/163716188/a6bd7340-63d2-4787-8c00-046eab8b8094)

Nejde ani presunúť súbor do externého prehrávača napíše - "preberanie súborov je zakázané".
Ale to nevadí, lebo na lg tak či tak, nie je spolahlívy externý prehrávač.

Treba niakym spôsobom to fixnúť aby prehralo streamy na LG telke cez ich Web normálny. Predtým to išlo uplne vpohode, predtým ako sa skryli linky.

Teraz nájde streamy všetko vpohode ako predtým, len ich neprehrá.

**Comment by ropmansk** [comment]
Problem moze byt v tom ze sa generuju linky s http a nie https -> http://stremio-cinema.vercel.app/stream/url/... ktore potom redirectuju na https link.
S tymto mozu mat problem niektore browsery a to je asi dovod preco to nefunguje. Staci vygenerovat https link a tym sa to pravdepodobne fixne.

`Mixed Content: The page at 'https://web.stremio.com/#/player/...' was loaded over HTTPS, but requested an insecure resource 'http://stremio-cinema.vercel.app/stream/url/...'. This request has been blocked; the content must be served over HTTPS.`

**Comment by strof1x** [comment]
BUMP

**Comment by ljsydpwym** [comment]
Podla vsetkeho fixnute s commitom: a605b9a755dfa5c381c513a2d56416aaeea8c14e
Prosim o oskusanie.
