### ISSUE TITLE
Problém s limitem 1000 u seriálů bez sérií.

### ISSUE THREAD

**Issue by noreithe** [ljsydpwym/StremioCinema#21]
Ahoj,
pokud má seriál více dílů než 1000 (ano, je to Ordinace...), tak je Stremio schopne najit cokoliv k prehrani jen do dilu 1000, dál už nenajde nic. Stejnou věc jsme řešili na scc pluginu do kodi, kte stačilo zvednout limit 1000.
Lze ten limit navýšit i v tomtu pluginu?
Díky

**Comment by ljsydpwym** [comment]
Fixed 1.0.1
