### ISSUE TITLE
Implementácia bingeGroup (Autoplay na seriáloch)

### ISSUE THREAD

**Issue by youchi1** [ljsydpwym/StremioCinema#3]
Ahojte,

aktuálne je nutné po každej časti seriálu manuálne spúšťať ďalšiu. Vďaka bingeGroup by sa automaticky vedela spustiť ďalčia časť seriálu z rovnakej skupiny, ktorá by mohla byť napr definovaná ako StremioCinema_Kvalita_VsetkyJazykyDabingu.

"bingeGroup: if defined, addons with the same behaviorHints.bingeGroup will be chosen automatically for binge watching; this should be something that identifies the stream's nature within your addon: for example, if your addon is called "gobsAddon", and the stream is 720p, the bingeGroup should be "gobsAddon-720p"; if the next episode has a stream with the same bingeGroup, stremio should select that stream implicitly" ( https://github.com/Stremio/stremio-addon-sdk/blob/45b3c79acb77a747a849c9950274f8b9b51a2035/docs/api/responses/stream.md?plain=1#L26 )

J

**Comment by ljsydpwym** [comment]
Implemented by @Airsane  in https://github.com/ljsydpwym/StremioCinema/pull/7
