### ISSUE TITLE
Možnosť nastavenia pluginu

### ISSUE THREAD

**Issue by youchi1** [ljsydpwym/StremioCinema#4]
Ahojte,

myslím, že by bolo fajn mať možnosť nastaviť pár vecí v štýle Torrentia:
![image](https://github.com/ljsydpwym/StremioCinema/assets/67028235/c890584e-000a-4e61-9614-59fd09a243ad)
https://torrentio.strem.fun/configure

Napríklad:
1. Priority foreign language:
2. Sorting
- By then Priority Language
- By Language then Quality
- By quality then size
- ...
3. Exclude qualities/resolutions:
4. Max results per quality:
5. Video size limit:

J

**Comment by ljsydpwym** [comment]
Implementovane. Pre konkretne chybajuce nastavenia mozme pokracovat dalsimi issues.
